# Combinatoire du [Puissance 4](https://fr.wikipedia.org/wiki/Puissance_4)
>**Objectif** : Implémentation du jeu + Étude combinatoire du jeu

---

## Membres du binômes
### VU Hoang Thuy Duong
[LinkedIn](https://www.linkedin.com/in/meriadocdgv/) | [Github](https://github.com/Meriadoc-gitgit)
- **Numéro d'étudiante : 21110221**
- Groupe : 1 *(Statistique et Informatique - LU3IN005)*
- Email : vuhoang.thduong@gmail.com
    
    
### Halimatou DIALLO
[LinkedIn](https://www.linkedin.com/in/diallo-halima/) | [Github](https://github.com/limadiallo)
- **Numéro d'étudiante : 21114613**
- Groupe : 1 *(Statistique et Informatique - LU3IN005)*
- Email : 
    
    
## Instructeur
### M. Maxime Bouthors
Adresse mail : bouthors@isir.upmc.fr

---

# Introduction
---

# Modèle basique

## Structures utilisées
### Class `Plateau`
- 1 tableau `self.board` de dimension `self.width`x`self.length` représentant le plateau de jeu
- 2 joueurs `self.player1` et `self.player2` 
- 2 variables enregistrant la dimension du plateau de jeu `self.width` et `self.length`

### Class `Player`
- 1 étiquette `self.etiquette` représentant la couleur possédée par ce joueur
- 1 ensemble de coordonnées `self.coordinate` de chaque tour du joueur

## Fonctions de manipulation
|Nom de fonction|Utilisation|
|---|---|
|`show()`|afficher le plateau en cours|
|`reset()`|réinitialiser le jeu|
|`has_won()`|tester la victoire d'un des deux joueurs|
|`play(x,joueur)`|placer un jeton dans la colonne `x` pour le joueur spécifié|
|`is_finished()`|tester si c’est la fin du jeu (plateau plein ou victoire d’un joueur)|
|`run(joueur1,joueur2)`|jouer une partie entre lejoueur 1 et le joueur 2|

In [1]:
# Import necessary libraries
import random
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Import necessary classes
from plateau import *
from player import *
from src import *


# Définir les 2 joueurs avec leurs propres étiquettes
# Symbole : 
### 1 pour le premier joueur
### -1 pour le deuxième
Joueur1 = Player(1)
Joueur2 = Player(-1)


# DÉMARRAGE DU JEU 
# Définir le Plateau de Puissance 4 sur laquelle le jeu démarre

# Dimension 8x8
print("PUISSANCE 4 - DIMENSION 8x8")
P = Plateau(8,8,Joueur1,Joueur2)
P.run(Joueur1,Joueur2)
P.show()
print();print()

# Dimension 7x8
print("PUISSANCE 4 - DIMENSION 7x8")
P = Plateau(7,8,Joueur1,Joueur2)
P.run(Joueur1,Joueur2)
P.show()
print();print()

# Dimension 8x9
print("PUISSANCE 4 - DIMENSION 8x9")
P = Plateau(8,9,Joueur1,Joueur2)
P.run(Joueur1,Joueur2)
P.show()

PUISSANCE 4 - DIMENSION 8x8
Current state of the game
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  0. -1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1. -1.  1.]]


PUISSANCE 4 - DIMENSION 7x8
Current state of the game
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -1.  0.  0.  0. -1.  0.  0.]
 [ 1.  1. -1.  0.  0. -1.  0.  0.]
 [-1. -1.  1.  0.  0. -1.  1.  0.]
 [ 1.  1. -1. -1.  1. -1.  1.  0.]]


PUISSANCE 4 - DIMENSION 8x9
Current state of the game
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1. -1. -1.  1. -1.]
 [ 0. -1. -1.  1. -1. -1.  1. -1. 

---

# Étude de la Distribution du nombre de coups avant une victoire

In [2]:
# Importer la df générée précédemment
df = pd.read_csv("freq_moves_database.csv") # Delimiter unnecessary as it's a simple df

![](poisson_dist_nb_coups.jpg)
![](poisson_dist_nb_coups_classified.jpg)

## Processus
Afin d'étudier la distribution du nombre de coups *avant une victoire lorsque les deux joueurs
jouent aléatoirement en différenciant selon que ce soit le premier ou le deuxième joueur qui gagne*, nous regénérons 1000 fois le moteur automatique du jeu.

Après avoir obtenu les résultats et passé par des traitements afin de raccourcir les opérations et de créer des bases de données nécessaires, nous trouvons que le nombre de coups avant une victoire suit la **loi de Poisson**, *et n'est pas normale*. 

### [Loi de Poisson](https://fr.wikipedia.org/wiki/Loi_de_Poisson)
En théorie des probabilités et en statistiques, la loi de Poisson est une loi de probabilité discrète qui décrit **le comportement du nombre d'événements se produisant dans un intervalle de temps fixé**, si ces événements se produisent avec une fréquence moyenne ou espérance connue, et indépendamment du temps écoulé depuis l'événement précédent.

La loi de Poisson est également pertinente pour décrire le nombre d'événements dans d'autres types d'intervalles, spatiaux plutôt que temporels, comme des segments, surfaces ou volumes.

<img src="poisson_masse.png" alt="Fonction de masse de la loi de Poisson" width="300"/>

### Explication


---

---

[Loi de Poisson](https://fr.wikipedia.org/wiki/Loi_de_Poisson)